**Supervised** **Word** **Embedding**

In [ ]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Input
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [ ]:
reviews=[
    'nice food',
    'amazing resturant',
    'quality items',
    'good taste',
    'must try this',
    'poor quality',
    'less services',
    'consumes more time',
    'poor taste',
    'never again'
]
sentiment=np.array([1,1,1,1,1,0,0,0,0,0])

In [ ]:
one_hot("amazing restaurant",30)

[6, 19]

In [ ]:
vocab_size=30
encoded_reviews=[one_hot(d,vocab_size) for d in reviews]
print(encoded_reviews)

[[28, 10], [6, 23], [8, 20], [16, 26], [18, 16, 3], [3, 8], [10, 27], [19, 12, 21], [3, 26], [10, 28]]


In [ ]:
max_length=4
padded_reviews=pad_sequences(encoded_reviews,maxlen=max_length,padding='post')
print(padded_reviews)

[[28 10  0  0]
 [ 6 23  0  0]
 [ 8 20  0  0]
 [16 26  0  0]
 [18 16  3  0]
 [ 3  8  0  0]
 [10 27  0  0]
 [19 12 21  0]
 [ 3 26  0  0]
 [10 28  0  0]]


In [ ]:
embedded_vector_size=5
model=Sequential()
model.add(Input(shape=(max_length,)))
model.add(Embedding(vocab_size,embedded_vector_size,name='embedding'))
model.add(Flatten())
model.add(Dense(1,activation='sigmoid'))

In [ ]:
X=padded_reviews
y=sentiment

In [ ]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)
print(model.summary())

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 4, 5)           │           150 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_5 (Flatten)             │ (None, 20)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            21 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 171 (684.00 B)

 Trainable params: 171 (684.00 B)

 Non-trainable params: 0 (0.00 B)

None


In [ ]:
model.fit(X,y,epochs=50,verbose=0)

In [ ]:
loss,accuracy=model.evaluate(X,y)
accuracy

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step - accuracy: 1.0000 - loss: 0.6361


1.0

In [ ]:
weights=model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [ ]:
weights[13]

array([-0.03873608, -0.02862531,  0.03591662,  0.02437619, -0.00606896],
      dtype=float32)

In [ ]:
weights[4]

array([-0.01751571, -0.0172195 , -0.01462061,  0.01285391,  0.01935109],
      dtype=float32)

In [ ]:
weights[13]

array([-0.03873608, -0.02862531,  0.03591662,  0.02437619, -0.00606896],
      dtype=float32)